version: '3.7'

services:
  db:
    container_name: beta_db
    image: mongo:latest
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/database
    environment: 
      - MONGO_INITDB_DATABASE= BetaDB
  
  backend:
      container_name: beta_backend
      command: npm start
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes: 
        - ./backend:/backend
      ports:
        - '5050:5050'
      depends_on: 
        - db

  # frontend:
  #     container_name: beta_frontend
  #     command: yarn start
  #     build:
  #       context: ./frontend
  #       dockerfile: Dockerfile
  #     volumes:
  #       - ./frontend:/frontend
  #     ports:
  #       - '3000:3000'
  #     depends_on: 
  #       - backend 